### ISSUE TITLE
Hotmail throws a timeout

### ISSUE THREAD

**Issue by mickaelchanrion** [brandon93s/email-chk#1]
Hi, 
Thank you for this utility.

But it appears that emails from hotmail throws a timeout. Do you have any clue to fix this?

Thks by advance :)

**Comment by brandon93s** [comment]
It looks like hotmail, outlook, live, etc. don't allow SMTP connections from unverifiable addresses. You'd likely have to initiate the `email-chk` command from a properly configured SMTP server box (and IP) for the connection to be accepted.
